#!/bin/sh
# VARIABLES DE ENTORNO LOCALES
export APP_SERVICE_NAME="app-backend-hfg3u4is4wihs"
export RESOURCE_GROUP_NAME="rg-poc-rag-peru"
export APP_SERVICE_PLAN="plan-hfg3u4is4wihs"
export AZURE_STORAGE_CONTAINER="content"
export AZURE_OPENAI_SERVICE="cog-gunbku7vcuucu"
export AZURE_OPENAI_RESOURCE_GROUP="rg-sample-ntt-openai-dev"
export AZURE_OPENAI_CHATGPT_MODEL="gpt-35-turbo"
export AZURE_OPENAI_CHATGPT_DEPLOYMENT="chat"
export AZURE_OPENAI_EMB_DEPLOYMENT="embedding-ada"
export AZURE_SEARCH_SERVICE="gptkb-hfg3u4is4wihs"
export AZURE_SEARCH_SERVICE_RESOURCE_GROUP="rg-poc-rag-peru"
export AZURE_SEARCH_INDEX="demo-rimac"
export AZURE_FORMRECOGNIZER_SERVICE="cog-fr-hfg3u4is4wihs"
export AZURE_FORMRECOGNIZER_RESOURCE_GROUP="rg-poc-rag-peru"
export AZURE_STORAGE_ACCOUNT="sthfg3u4is4wihs"
export AZURE_STORAGE_RESOURCE_GROUP="rg-poc-rag-peru"
export AZURE_SERVER_APP_ID="app-backend-hfg3u4is4wihs"
export AZURE_USE_AUTHENTICATION=false
